using System.Globalization;
using System.Text;
using TerraFluent.AutoAnalytics.Agent;
using TerraFluent.AutoAnalytics.Agent.Skills;
using TerraFluent.AutoAnalytics.Analytics;
using TerraFluent.AutoAnalytics.Data.Sources;
using TerraFluent.AutoAnalytics.Data;
using TerraFluent.AutoAnalytics.Engine;
using TerraFluent.AutoAnalytics.Enums;
using TerraFluent.AutoAnalytics.Insights;
using TerraFluent.AutoAnalytics.Recommendation;

namespace TerraFluent.Chart.Reporting.Samples;

/// <summary>
/// Showcases the TerraFluent.AutoAnalytics <b>agent</b> features added on top of the one-shot engine:
/// the deterministic planner (ask a question → explainable reasoning trace), forecasting, root-cause,
/// segmentation, period-over-period comparison, multi-turn session memory, multi-dimension
/// aggregation and row filtering. Writes <c>agent-report.html</c> to the output folder.
/// </summary>
internal static class AutoAnalyticsAgentSample
{
    public static void Generate(string outputDir)
    {
        string csv = BuildSalesCsv();
        var dataset = new CsvDataSource(csv, name: "Global Sales 2023–2024").Load();
        AnalyticsResult result = new AnalyticsEngine().Run(dataset, new AnalyticsOptions
        {
            DatasetName = "Global Sales 2023–2024",
            MaxRecommendations = 24
        });

        var agent = BuildAgent();

        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>AutoAnalytics Agent — Feature Showcase</title>");
        sb.AppendLine(Styles());
        sb.AppendLine("</head><body>");

        var s = result.Summary;
        sb.AppendLine("<header class=\"hero\">");
        sb.AppendLine("  <h1>AutoAnalytics Agent — Feature Showcase</h1>");
        sb.AppendLine("  <p class=\"headline\">A deterministic, non-AI analytic agent: ask a question, get an explainable plan.</p>");
        sb.AppendLine("  <div class=\"meta\">");
        sb.AppendLine($"    <span>{s.RowCount} rows</span><span>{s.ColumnCount} columns</span>");
        sb.AppendLine($"    <span>{s.MeasureCount} measures</span><span>{s.DimensionCount} dimensions</span>");
        sb.AppendLine($"    <span>Data quality: {Enc(s.DataQuality)}</span>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</header><main>");

        // 1) Ask the agent a range of questions — each renders a full reasoning trace.
        sb.AppendLine("<section><h2>1 · Ask the agent</h2>");
        sb.AppendLine("<p class=\"lead\">Each question is parsed into a goal, the planner selects skills, follows the evidence " +
                      "(e.g. a trend triggers a forecast + root-cause), and returns an explainable trace.</p>");
        string?[] questions =
        {
            null,                                   // open-ended exploration
            "forecast revenue",
            "why did revenue change?",
            "compare revenue month over month",
            "segment the data into natural groups",
            "which region leads revenue?"
        };
        foreach (var q in questions)
            RenderTrace(sb, agent.Investigate(result, q), q);
        sb.AppendLine("</section>");

        // 2) Multi-turn session with memory + pronoun resolution.
        sb.AppendLine("<section><h2>2 · Multi-turn session (memory)</h2>");
        sb.AppendLine("<p class=\"lead\">The session remembers prior turns, never repeats analysis, and resolves pronouns " +
                      "(\"forecast <em>it</em>\") to the previous focus.</p>");
        RenderSession(sb, agent, result);
        sb.AppendLine("</section>");

        // 3) Multi-dimension aggregation (pivot).
        sb.AppendLine("<section><h2>3 · Aggregation pivot</h2>");
        sb.AppendLine("<p class=\"lead\">Average Revenue by Region × Product.</p>");
        RenderPivot(sb, new AggregationEngine()
            .GroupBy(result.Profile, "Revenue", "Region", "Product", AggregationKind.Average));
        sb.AppendLine("</section>");

        // 4) Row filtering (slice) before analysis.
        sb.AppendLine("<section><h2>4 · Filtered slice</h2>");
        RenderFilter(sb, dataset);
        sb.AppendLine("</section>");

        sb.AppendLine("</main>");
        sb.AppendLine("<footer>Generated by TerraFluent.AutoAnalytics — deterministic, explainable, no AI.</footer>");
        sb.AppendLine("</body></html>");

        File.WriteAllText(Path.Combine(outputDir, "agent-report.html"), sb.ToString(), Encoding.UTF8);
    }

    private static AnalyticAgent BuildAgent() => new(
        new AnalyticsEngine(),
        new IAnalyticSkill[]
        {
            new TrendSkill(), new AnomalySkill(), new CorrelationSkill(), new DominanceSkill(),
            new ForecastSkill(), new RootCauseSkill(), new SegmentSkill(), new ComparisonSkill()
        });

    // ── Rendering ────────────────────────────────────────────────────────────────

    private static void RenderTrace(StringBuilder sb, InvestigationTrace trace, string? question)
    {
        sb.AppendLine("<div class=\"card\">");
        sb.AppendLine($"  <div class=\"q\">{Enc(question is null ? "(open-ended exploration)" : "“" + question + "”")}</div>");
        sb.AppendLine($"  <div class=\"hl\">{Enc(trace.Headline)}</div>");
        sb.AppendLine($"  <div class=\"narr\">{Enc(trace.Narrative)}</div>");

        if (trace.Steps.Count > 0)
        {
            sb.AppendLine("  <div class=\"steps\"><h4>Reasoning path</h4><ol>");
            foreach (var step in trace.Steps)
            {
                sb.Append("    <li><span class=\"skill\">").Append(Enc(step.SkillName)).Append("</span> ");
                sb.Append(Enc(step.Rationale));
                if (!string.IsNullOrEmpty(step.Trigger))
                    sb.Append("<span class=\"trigger\">↳ ").Append(Enc(step.Trigger!)).Append("</span>");
                sb.AppendLine("</li>");
            }
            sb.AppendLine("  </ol></div>");
        }

        RenderInsights(sb, trace.Insights);
        RenderCharts(sb, trace.Charts);
        sb.AppendLine("</div>");
    }

    private static void RenderInsights(StringBuilder sb, IReadOnlyList<Insight> insights)
    {
        if (insights.Count == 0) return;
        sb.AppendLine("  <ul class=\"insights\">");
        foreach (var i in insights.Take(6))
        {
            sb.AppendLine("    <li>");
            sb.AppendLine($"      <span class=\"score\">{i.ImportanceScore}</span>");
            sb.AppendLine($"      <div><strong>{Enc(i.Title)}</strong><span>{Enc(i.Description)}</span></div>");
            sb.AppendLine("    </li>");
        }
        sb.AppendLine("  </ul>");
    }

    private static void RenderCharts(StringBuilder sb, IReadOnlyList<RecommendedChart> charts)
    {
        if (charts.Count == 0) return;
        sb.AppendLine("  <div class=\"charts\">");
        foreach (var chart in charts.Take(4))
        {
            string svg = ChartConfigBuilder.ToChartBuilder(chart.Spec).AsAnimated().Size(480, 300).RenderToSvg();
            sb.AppendLine($"    <figure>{svg}<figcaption>{Enc(chart.Reason)}</figcaption></figure>");
        }
        sb.AppendLine("  </div>");
    }

    private static void RenderSession(StringBuilder sb, AnalyticAgent agent, AnalyticsResult result)
    {
        var session = agent.StartSession(result);
        string[] turns =
        {
            "what is the revenue trend?",
            "now forecast it",
            "and compare it month over month",
            "which region drives it?"
        };

        sb.AppendLine("<div class=\"chat\">");
        foreach (var q in turns)
        {
            var trace = session.Ask(q);
            sb.AppendLine($"  <div class=\"bubble user\">{Enc(q)}</div>");
            sb.AppendLine("  <div class=\"bubble agent\">");
            sb.AppendLine($"    <strong>{Enc(trace.Headline)}</strong>");
            sb.AppendLine($"    <span class=\"narr\">{Enc(trace.Narrative)}</span>");
            if (trace.Steps.Count > 0)
                sb.AppendLine($"    <span class=\"chips\">{string.Join(" ", trace.Steps.Select(st => $"<em>{Enc(st.SkillName)}</em>"))}</span>");
            sb.AppendLine("  </div>");
        }
        sb.AppendLine("</div>");
    }

    private static void RenderPivot(StringBuilder sb, AggregationResult? agg)
    {
        if (agg is null || !agg.IsPivot) { sb.AppendLine("<p>No pivot available.</p>"); return; }

        sb.AppendLine("<table class=\"pivot\"><thead><tr><th></th>");
        foreach (var col in agg.ColumnKeys) sb.Append("<th>").Append(Enc(col)).Append("</th>");
        sb.AppendLine("</tr></thead><tbody>");
        foreach (var row in agg.RowKeys)
        {
            sb.Append("<tr><th>").Append(Enc(row)).Append("</th>");
            foreach (var col in agg.ColumnKeys)
            {
                var cell = agg.Cells.FirstOrDefault(c => c.Row == row && c.Column == col);
                string v = cell is null ? "—" : FormatNumber(cell.Value);
                sb.Append("<td>").Append(Enc(v)).Append("</td>");
            }
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</tbody></table>");
    }

    private static void RenderFilter(StringBuilder sb, Dataset dataset)
    {
        const string expr = "Region = Europe and Revenue > 20000";
        var filtered = SliceExpression.Parse(expr).Apply(dataset);
        var filteredResult = new AnalyticsEngine().Run(filtered, new AnalyticsOptions { DatasetName = "Europe (high revenue)" });

        sb.AppendLine($"<p class=\"lead\">Filter <code>{Enc(expr)}</code> keeps {filtered.RowCount} of {dataset.RowCount} rows.</p>");
        sb.AppendLine($"<div class=\"card\"><div class=\"hl\">{Enc(filteredResult.Summary.Headline)}</div>");
        RenderInsights(sb, filteredResult.Insights.Take(3).ToList());
        sb.AppendLine("</div>");
    }

    // ── Sample data: 24 monthly rows across 2 years, 3 regions/products, rising revenue + one spike ──
    private static string BuildSalesCsv()
    {
        var sb = new StringBuilder();
        sb.AppendLine("Month,Region,Product,Revenue,Cost,Units");
        string[] regions = { "North America", "Europe", "Asia Pacific" };
        string[] products = { "Alpha", "Beta", "Gamma" };
        var start = new DateTime(2023, 1, 1);

        for (int i = 0; i < 24; i++)
        {
            var month = start.AddMonths(i);
            string region = regions[i % regions.Length];
            string product = products[(i / 2) % products.Length];

            double baseRevenue = 12000 + i * 650 + Math.Sin(i / 2.0) * 1400;
            if (i == 15) baseRevenue *= 3.1; // deliberate anomaly

            double revenue = Math.Round(baseRevenue, 0);
            double cost = Math.Round(revenue * (0.55 + (i % 3) * 0.03), 0);
            int units = (int)Math.Round(revenue / 95.0);

            sb.AppendLine(string.Join(",",
                month.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
                region, product,
                revenue.ToString(CultureInfo.InvariantCulture),
                cost.ToString(CultureInfo.InvariantCulture),
                units.ToString(CultureInfo.InvariantCulture)));
        }
        return sb.ToString();
    }

    private static string FormatNumber(double v)
    {
        double a = Math.Abs(v);
        return a switch
        {
            >= 1_000_000 => (v / 1_000_000).ToString("0.##", CultureInfo.InvariantCulture) + "M",
            >= 1_000     => (v / 1_000).ToString("0.##", CultureInfo.InvariantCulture) + "k",
            _            => v.ToString("0.##", CultureInfo.InvariantCulture)
        };
    }

    private static string Enc(string value) => value
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private static string Styles() => """
        <style>
          * { box-sizing: border-box; }
          body { margin:0; font-family:'Segoe UI',system-ui,sans-serif; background:#f1f5f9; color:#1e293b; }
          .hero { background:linear-gradient(135deg,#0ea5e9,#6366f1); color:#fff; padding:32px 40px; }
          .hero h1 { margin:0 0 6px; font-size:28px; }
          .hero .headline { margin:0 0 14px; font-size:16px; opacity:.92; }
          .meta { display:flex; flex-wrap:wrap; gap:10px; font-size:13px; }
          .meta span { background:rgba(255,255,255,.18); padding:4px 12px; border-radius:999px; }
          main { padding:28px 40px; max-width:1180px; margin:0 auto; }
          section { margin-bottom:40px; }
          section h2 { font-size:20px; margin:0 0 6px; color:#334155; }
          .lead { color:#64748b; margin:0 0 18px; font-size:14px; }
          .card { background:#fff; border-radius:14px; padding:20px; margin-bottom:18px; box-shadow:0 1px 3px rgba(0,0,0,.08); }
          .q { font-size:16px; font-weight:700; color:#6366f1; margin-bottom:6px; }
          .hl { font-size:16px; font-weight:600; }
          .narr { color:#64748b; font-size:13px; display:block; margin:4px 0 10px; }
          .steps h4 { margin:12px 0 6px; font-size:13px; text-transform:uppercase; letter-spacing:.04em; color:#94a3b8; }
          .steps ol { margin:0; padding-left:18px; }
          .steps li { font-size:13px; margin-bottom:6px; color:#334155; }
          .skill { display:inline-block; background:#eef2ff; color:#4f46e5; font-weight:600; font-size:12px; padding:1px 8px; border-radius:999px; margin-right:6px; }
          .trigger { display:block; color:#94a3b8; font-size:12px; margin-left:6px; }
          ul.insights { list-style:none; margin:14px 0 0; padding:0; display:flex; flex-direction:column; gap:8px; }
          ul.insights li { display:flex; gap:10px; align-items:flex-start; background:#f8fafc; border-radius:10px; padding:10px 12px; }
          ul.insights .score { background:#6366f1; color:#fff; font-weight:700; border-radius:8px; padding:3px 9px; font-size:12px; min-width:32px; text-align:center; }
          ul.insights strong { display:block; font-size:14px; }
          ul.insights span { color:#64748b; font-size:13px; }
          .charts { display:grid; grid-template-columns:repeat(auto-fit,minmax(400px,1fr)); gap:16px; margin-top:16px; }
          .charts figure { margin:0; min-width:0; background:#fbfcfe; border-radius:10px; padding:12px; }
          .charts figure svg { display:block; width:100%; height:auto; }
          .charts figcaption { margin-top:8px; font-size:12px; color:#64748b; }
          .chat { display:flex; flex-direction:column; gap:10px; }
          .bubble { max-width:80%; padding:12px 16px; border-radius:14px; font-size:14px; }
          .bubble.user { align-self:flex-end; background:#6366f1; color:#fff; border-bottom-right-radius:4px; }
          .bubble.agent { align-self:flex-start; background:#fff; box-shadow:0 1px 3px rgba(0,0,0,.08); border-bottom-left-radius:4px; }
          .bubble.agent .narr { margin:4px 0 0; }
          .chips em { font-style:normal; background:#eef2ff; color:#4f46e5; font-size:11px; font-weight:600; padding:1px 7px; border-radius:999px; margin-right:4px; }
          table.pivot { border-collapse:collapse; background:#fff; border-radius:12px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,.08); }
          table.pivot th, table.pivot td { padding:10px 16px; text-align:right; font-size:14px; border-bottom:1px solid #f1f5f9; }
          table.pivot thead th { background:#f8fafc; color:#475569; font-size:12px; text-transform:uppercase; letter-spacing:.04em; }
          table.pivot tbody th { text-align:left; color:#334155; }
          code { background:#eef2ff; color:#4f46e5; padding:2px 6px; border-radius:6px; font-size:13px; }
          footer { text-align:center; padding:20px; color:#94a3b8; font-size:13px; }
        </style>
        """;
}
