using System.Text;
using TerraFluent.AutoAnalytics.Dashboard;
using TerraFluent.AutoAnalytics.Engine;
using TerraFluent.AutoAnalytics.Recommendation;
using TerraFluent.Chart.Reporting.Api.Models;

namespace TerraFluent.Chart.Reporting.Api.Rendering;

/// <summary>
/// Renders a <see cref="DashboardDefinition"/> into a self-contained HTML page (KPIs, chart
/// sections with inline SVG, anomalies and insight panels). Mirrors the sample dashboard output.
/// </summary>
internal static class DashboardHtmlRenderer
{
    public static string Render(DashboardDefinition dashboard, AnalyticsResult result, ChartStyle style = default)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine($"<title>{Enc(dashboard.Title)}</title>");
        sb.AppendLine(EmbeddedFontCss.StyleBlock);
        sb.AppendLine(Styles());
        sb.AppendLine("</head><body>");

        var s = result.Summary;
        sb.AppendLine("<header class=\"hero\">");
        sb.AppendLine($"  <h1>{Enc(dashboard.Title)}</h1>");
        sb.AppendLine($"  <p class=\"headline\">{Enc(s.Headline)}</p>");
        sb.AppendLine("  <div class=\"meta\">");
        sb.AppendLine($"    <span>{s.RowCount} rows</span><span>{s.ColumnCount} columns</span>");
        sb.AppendLine($"    <span>{s.MeasureCount} measures</span><span>{s.DimensionCount} dimensions</span>");
        sb.AppendLine($"    <span class=\"quality quality-{s.DataQuality.ToLowerInvariant()}\">Data quality: {Enc(s.DataQuality)}</span>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</header><main>");

        if (dashboard.Kpis.Count > 0)
        {
            sb.AppendLine("<section><h2>Executive KPIs</h2><div class=\"kpi-grid\">");
            foreach (var kpi in dashboard.Kpis)
            {
                sb.AppendLine("  <div class=\"kpi\">");
                sb.AppendLine($"    <div class=\"kpi-value\">{Enc(kpi.DisplayValue)}</div>");
                sb.AppendLine($"    <div class=\"kpi-label\">{Enc(kpi.Label)}</div>");
                if (!string.IsNullOrEmpty(kpi.Caption))
                    sb.AppendLine($"    <div class=\"kpi-caption\">{Enc(kpi.Caption!)}</div>");
                sb.AppendLine("  </div>");
            }
            sb.AppendLine("</div></section>");
        }

        Section(sb, "Trends", dashboard.TrendCharts, style);
        Section(sb, "Category comparisons", dashboard.ComparisonCharts, style);
        Section(sb, "Distributions", dashboard.DistributionCharts, style);

        if (dashboard.Anomalies.Count > 0)
        {
            sb.AppendLine("<section><h2>Anomalies detected</h2><ul class=\"panel anomalies\">");
            foreach (var a in dashboard.Anomalies)
            {
                sb.AppendLine("  <li>");
                sb.AppendLine($"    <span class=\"score tip\" data-tip=\"Severity score (0\u2013100): how far this anomaly stands out from the norm\">{a.ImportanceScore}</span>");
                sb.AppendLine($"    <div><strong>{Enc(a.Title)}</strong><span>{Enc(a.Description)}</span></div>");
                sb.AppendLine("  </li>");
            }
            sb.AppendLine("</ul></section>");
        }

        sb.AppendLine("<section><h2>Key insights</h2><ul class=\"panel insights\">");
        foreach (var insight in dashboard.KeyInsights)
        {
            sb.AppendLine("  <li>");
            sb.AppendLine($"    <span class=\"score tip\" data-tip=\"Importance score (0\u2013100): how noteworthy this insight is\">{insight.ImportanceScore}</span>");
            sb.AppendLine($"    <div><strong>{Enc(insight.Title)}</strong><span>{Enc(insight.Description)}</span></div>");
            sb.AppendLine("  </li>");
        }
        sb.AppendLine("</ul></section>");

        sb.AppendLine("</main>");
        sb.AppendLine("<footer>Generated by TerraFluent.AutoAnalytics — deterministic, no AI.</footer>");
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    private static void Section(StringBuilder sb, string title, IReadOnlyList<RecommendedChart> charts, ChartStyle style = default)
    {
        if (charts.Count == 0) return;
        sb.AppendLine($"<section><h2>{Enc(title)}</h2><div class=\"chart-grid\">");
        foreach (var chart in charts)
        {
            string svg = style.Apply(ChartConfigBuilder.ToChartBuilder(chart.Spec).Size(560, 340))
                .RenderToSvg();

            sb.AppendLine("  <figure class=\"chart-card\">");
            sb.AppendLine($"    <div class=\"chart-badge\">{Enc(chart.ChartName)} · score {chart.SuitabilityScore}</div>");
            sb.AppendLine($"    {svg}");
            sb.AppendLine($"    <figcaption>{Enc(chart.Reason)}</figcaption>");
            sb.AppendLine("  </figure>");
        }
        sb.AppendLine("</div></section>");
    }

    private static string Enc(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\"", "&quot;");

    private static string Styles() => """
        <style>
          * { box-sizing: border-box; }
          body { margin:0; font-family:'Inter','Segoe UI',system-ui,sans-serif; background:#f1f5f9; color:#1e293b; }
          .hero { background:linear-gradient(135deg,#4f46e5,#7c3aed); color:#fff; padding:32px 40px; }
          .hero h1 { margin:0 0 6px; font-size:28px; }
          .hero .headline { margin:0 0 14px; font-size:16px; opacity:.92; }
          .meta { display:flex; flex-wrap:wrap; gap:10px; }
          .meta span { background:rgba(255,255,255,.15); padding:4px 12px; border-radius:999px; font-size:13px; }
          .quality-clean { background:rgba(34,197,94,.35) !important; }
          .quality-warnings { background:rgba(234,179,8,.4) !important; }
          .quality-errors { background:rgba(239,68,68,.45) !important; }
          main { padding:28px 40px; max-width:1280px; margin:0 auto; }
          section { margin-bottom:34px; }
          section h2 { font-size:18px; margin:0 0 16px; color:#334155; }
          .kpi-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:16px; }
          .kpi { background:#fff; border-radius:14px; padding:20px; box-shadow:0 1px 3px rgba(0,0,0,.08); }
          .kpi-value { font-size:28px; font-weight:700; color:#4f46e5; }
          .kpi-label { font-size:15px; font-weight:600; margin-top:4px; }
          .kpi-caption { font-size:12px; color:#64748b; margin-top:2px; }
          .chart-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(420px,1fr)); gap:20px; }
          .chart-card { margin:0; background:#fff; border-radius:14px; padding:16px; box-shadow:0 1px 3px rgba(0,0,0,.08); }
          .chart-badge { display:inline-block; background:#eef2ff; color:#4f46e5; font-size:12px; font-weight:600; padding:3px 10px; border-radius:999px; margin-bottom:10px; }
          .chart-card figcaption { margin-top:10px; font-size:13px; color:#64748b; }
          .panel { list-style:none; margin:0; padding:0; display:flex; flex-direction:column; gap:10px; }
          .panel li { background:#fff; border-radius:12px; padding:14px 16px; box-shadow:0 1px 3px rgba(0,0,0,.06); display:flex; gap:12px; align-items:flex-start; }
          .panel strong { display:block; }
          .panel span { color:#64748b; font-size:14px; }
          .anomalies li { border-left:4px solid #ef4444; }
          .anomalies .score { background:#ef4444; color:#fff; font-weight:700; border-radius:8px; padding:4px 10px; font-size:13px; min-width:34px; text-align:center; }
          .insights .score { background:#5b21b6; color:#fff; font-weight:700; border-radius:8px; padding:4px 10px; font-size:13px; min-width:34px; text-align:center; }
          .tip { position:relative; }
          .tip::after { content:attr(data-tip); position:absolute; left:0; bottom:calc(100% + 9px); width:max-content; max-width:240px; white-space:normal; text-align:left; background:#1e293b; color:#fff; font-size:12px; font-weight:500; line-height:1.4; padding:8px 10px; border-radius:8px; box-shadow:0 8px 24px rgba(15,23,42,.22); opacity:0; visibility:hidden; transform:translateY(4px); transition:opacity .15s ease, transform .15s ease; pointer-events:none; z-index:60; }
          .tip::before { content:""; position:absolute; left:16px; bottom:calc(100% + 3px); border:6px solid transparent; border-top-color:#1e293b; opacity:0; visibility:hidden; transition:opacity .15s ease; pointer-events:none; z-index:60; }
          .tip:hover::after { opacity:1; visibility:visible; transform:translateY(0); }
          .tip:hover::before { opacity:1; visibility:visible; }
          footer { text-align:center; padding:20px; color:#94a3b8; font-size:13px; }
        </style>
        """;
}
