# Downloads a curated set of open-source Google Fonts as local woff2 files
# and generates a fonts.css with @font-face rules. Run once; output is committed.
$ErrorActionPreference = 'Stop'

$fontsDir = Join-Path $PSScriptRoot '..\src\TerraFluent.Chart.Reporting.Web\wwwroot\fonts'
New-Item -ItemType Directory -Force -Path $fontsDir | Out-Null

# family display name -> (slug, css2 family query, weights)
$families = @(
    @{ Name = 'Inter';               Slug = 'inter';                Query = 'Inter:wght@400;500;600;700';             Weights = @(400,500,600,700) },
    @{ Name = 'Plus Jakarta Sans';   Slug = 'plus-jakarta-sans';    Query = 'Plus+Jakarta+Sans:wght@400;500;600;700'; Weights = @(400,500,600,700) },
    @{ Name = 'Source Serif 4';      Slug = 'source-serif-4';       Query = 'Source+Serif+4:wght@400;600;700';        Weights = @(400,600,700) },
    @{ Name = 'Space Grotesk';       Slug = 'space-grotesk';        Query = 'Space+Grotesk:wght@400;500;700';         Weights = @(400,500,700) },
    @{ Name = 'Atkinson Hyperlegible'; Slug = 'atkinson-hyperlegible'; Query = 'Atkinson+Hyperlegible:wght@400;700'; Weights = @(400,700) }
)

# Modern browser UA so the API returns woff2 rather than ttf.
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
$faceRules = New-Object System.Collections.Generic.List[string]

foreach ($fam in $families) {
    $url = "https://fonts.googleapis.com/css2?family=$($fam.Query)&display=swap"
    Write-Host "Fetching CSS for $($fam.Name)..."
    $css = Invoke-WebRequest -Uri $url -Headers @{ 'User-Agent' = $ua } -UseBasicParsing | Select-Object -ExpandProperty Content

    # Split into per-subset @font-face blocks; each is preceded by a /* subset */ comment.
    $blocks = [regex]::Matches($css, "/\*\s*(?<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?<body>[^}]*)\}")
    foreach ($b in $blocks) {
        $subset = $b.Groups['subset'].Value
        if ($subset -ne 'latin' -and $subset -ne 'latin-ext') { continue }
        $body   = $b.Groups['body'].Value
        $weight = [regex]::Match($body, "font-weight:\s*(?<w>\d+)").Groups['w'].Value
        $srcUrl = [regex]::Match($body, "src:\s*url\((?<u>[^)]+)\)").Groups['u'].Value
        $urange = [regex]::Match($body, "unicode-range:\s*(?<r>[^;]+);").Groups['r'].Value.Trim()
        if (-not $srcUrl) { continue }

        $fileName = "$($fam.Slug)-$weight-$subset.woff2"
        $dest = Join-Path $fontsDir $fileName
        Write-Host "  -> $fileName"
        Invoke-WebRequest -Uri $srcUrl -Headers @{ 'User-Agent' = $ua } -UseBasicParsing -OutFile $dest

        $faceRules.Add(@"
@font-face {
  font-family: '$($fam.Name)';
  font-style: normal;
  font-weight: $weight;
  font-display: swap;
  src: url('../fonts/$fileName') format('woff2');
  unicode-range: $urange;
}
"@)
    }
}

$header = @"
/* ==========================================================================
   Self-hosted open-source fonts (Google Fonts, SIL OFL / Apache-2.0).
   Generated by tools/download-fonts.ps1 - do not edit by hand.
   Families: Inter, Plus Jakarta Sans, Source Serif 4, Space Grotesk,
             Atkinson Hyperlegible.
   ========================================================================== */
"@

$cssOut = Join-Path $fontsDir '..\css\fonts.css'
Set-Content -Path $cssOut -Value ($header + "`n" + ($faceRules -join "`n")) -Encoding UTF8
Write-Host "Wrote $cssOut with $($faceRules.Count) @font-face rules."
